"""Run the SPARQL queries in queries/*.rq against the Ontop endpoint and validate them.

Each .rq file may carry, in header comments:
    # title: the description shown
    # sql: the equivalent SQL query on Postgres (the reference)
    # show-sql: yes   -> also prints the SQL reformulation produced by Ontop

Before the queries, it checks that the mappings do not assert rdf:type :Actor
or :Director - that is, that those types can only come from the rewriting.

Usage:
    docker compose up -d
    uv run validate_queries.py [filter]
"""

import io
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

import polars as pl
from rdflib import RDF, Graph, Namespace

ROOT = Path(__file__).parent
ENDPOINT = os.environ.get("ONTOP_ENDPOINT", "http://localhost:8080")
POSTGRES_URI = os.environ.get(
    "POSTGRES_URI", "postgresql://imdb:imdb@localhost:5432/imdb"
)
R2RML = Namespace("http://www.w3.org/ns/r2rml#")
IMDB = Namespace("http://www.example.org/imdb#")
# Types that may only show up through rewriting, never asserted by the mapping.
INFERRED_ONLY = {IMDB.Actor: ":Actor", IMDB.Director: ":Director"}


def check_no_materialized_types(mapping: Path) -> bool:
    """Check that the mappings do not assert the types that must come from rewriting.

    In R2RML a class can be asserted in two ways: `rr:class` on the subjectMap,
    or a predicateObjectMap with `rr:predicate rdf:type` - both are checked.
    """
    g = Graph().parse(mapping)
    asserted = set(g.objects(None, R2RML["class"]))
    for pom in g.subjects(R2RML.predicate, RDF.type):
        asserted |= set(g.objects(pom, R2RML.object))
        for om in g.objects(pom, R2RML.objectMap):
            asserted |= set(g.objects(om, R2RML.constant))
    hits = sorted(INFERRED_ONLY[c] for c in asserted & INFERRED_ONLY.keys())
    for h in hits:
        print(f"  materialized type found in the mapping: {h}")
    return not hits


def headers(text: str) -> dict[str, str]:
    """Extract the metadata from the '# key: value' comments at the top of a .rq file."""
    return dict(re.findall(r"^#\s*([\w-]+):\s*(.+)$", text, flags=re.MULTILINE))


def http(path: str, params: dict[str, str], accept: str, post: bool = False) -> str:
    """Make an HTTP request to the Ontop endpoint and return the response body."""
    data = urllib.parse.urlencode(params)
    if post:
        req = urllib.request.Request(
            f"{ENDPOINT}{path}", data=data.encode(), headers={"Accept": accept}
        )
    else:
        req = urllib.request.Request(f"{ENDPOINT}{path}?{data}", headers={"Accept": accept})
    with urllib.request.urlopen(req, timeout=600) as resp:
        return resp.read().decode()


def sparql(query: str) -> pl.DataFrame:
    """Run a SPARQL query on the endpoint and return the result as a DataFrame."""
    body = http("/sparql", {"query": query}, "text/csv", post=True)
    return pl.read_csv(io.StringIO(body), infer_schema=False)


def normalize(df: pl.DataFrame) -> list[tuple]:
    """Multiset comparison; numbers are compared as floats."""
    cols = []
    for name in df.columns:
        as_str = df[name].cast(pl.String)
        as_num = as_str.cast(pl.Float64, strict=False)
        cols.append(as_num if as_num.null_count() == as_str.null_count() else as_str)
    return sorted(zip(*cols), key=repr)


def main():
    query_filter = sys.argv[1] if len(sys.argv) > 1 else ""
    pl.Config.set_tbl_rows(30)
    pl.Config.set_fmt_str_lengths(60)
    pl.Config.set_tbl_hide_dataframe_shape(True)

    ok = check_no_materialized_types(ROOT / "obda" / "imdb.r2rml.ttl")
    print(
        f"[{'OK' if ok else 'FAIL'}] mappings free of rdf:type "
        f"{' / '.join(INFERRED_ONLY.values())}\n"
    )

    for path in sorted((ROOT / "queries").glob("*.rq")):
        if query_filter not in path.name:
            continue
        text = path.read_text()
        meta = headers(text)
        print(f"=== {path.name}: {meta.get('title', '')}")

        t0 = time.perf_counter()
        result = sparql(text)
        elapsed = time.perf_counter() - t0
        print(result)

        if meta.get("show-sql") == "yes":
            reformulation = http("/ontop/reformulate", {"query": text}, "text/plain")
            print("  SQL generated by Ontop:")
            print("    " + reformulation.strip().replace("\n", "\n    "))

        if "sql" in meta:
            expected = pl.read_database_uri(meta["sql"], POSTGRES_URI)
            match = normalize(result) == normalize(expected)
            ok &= match
            print(
                f"[{'OK' if match else 'FAIL'}] SPARQL ({result.height} rows, "
                f"{elapsed:.1f}s) == reference SQL ({expected.height} rows)"
            )
            if not match:
                print(expected)
        print()

    print("ALL CHECKS PASSED" if ok else "SOME CHECKS FAILED")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
