# title: Inferred typing of :Director (domains of :directed and :hasGenreAffinity)
# question: How many directors are there?
# show-sql: yes
# sql: SELECT COUNT(*) AS n FROM (SELECT director_id FROM movies_directors UNION SELECT director_id FROM directors_genres) t
PREFIX : <http://www.example.org/imdb#>

SELECT (COUNT(DISTINCT ?x) AS ?n)
WHERE { ?x a :Director }
