# title: Titles directed by Quentin Tarantino, in lexicographic order
# question: What are the titles of the films directed by Quentin Tarantino, in lexicographic order?
# sql: SELECT m.name AS title FROM directors d JOIN movies_directors md ON md.director_id = d.id JOIN movies m ON m.id = md.movie_id WHERE d.first_name = 'Quentin' AND d.last_name = 'Tarantino'
PREFIX :     <http://www.example.org/imdb#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?title
WHERE {
  ?d foaf:givenName "Quentin" ;
     foaf:familyName "Tarantino" ;
     :directed ?m .
  ?m :title ?title .
}
ORDER BY ?title
