# title: Cast of Reservoir Dogs with characters, ordered by first and last name
# question: What are the first names and last names of the actors who took part in the film Reservoir Dogs, in lexicographic order, with their respective characters?
# sql: SELECT a.first_name AS given, a.last_name AS family, NULLIF(r.role, '') AS character FROM movies m JOIN roles r ON r.movie_id = m.id JOIN actors a ON a.id = r.actor_id WHERE m.name = 'Reservoir Dogs'
PREFIX :     <http://www.example.org/imdb#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?given ?family ?character
WHERE {
  ?m :title "Reservoir Dogs" ;
     :hasActor ?a .
  ?a foaf:givenName ?given ;
     foaf:familyName ?family .
  OPTIONAL {
    ?p :performer ?a ;
       :performanceIn ?m ;
       :characterName ?character .
  }
}
ORDER BY ?given ?family ?character
